### ISSUE TITLE
basic release testing

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/doathon-dev#26]
- [x] link checking
- [x] mobile checking
- [ ] incognito testing
- [x] testing on main domain
- [x] ensure move to production issues

**Comment by JosephMcArthur** [comment]
Have done a bunch of re-org & notes to make this a touch easier

**Comment by JosephMcArthur** [comment]
# non-trivial fixes

* think about a tagging system so that global projects turn up in all sections
- [x] project name shows link, but often isn't linked NOW: #67 
* [x] add something about not needing to a dev to top tips NOW: #69 
- [x] on mobile text is only about 1/2 the screen. Should probably be more or less full width NOW: #68

**Comment by JosephMcArthur** [comment]
Stuff still to do: 
- [x] labels on main repo
- [x] check issue template on main repo
- [x] try and IRL walkthrough of everything one final time
- [x] double check emails sent my live
- [x] either turn off moderation for people, or leave it on

**Comment by char-siuu-bao** [comment]
@JosephMcArthur - trying to address as many of these as possible: 

- Do we need labels for issues on the main repo? I've restructured all the searches and links so that they are according to the #hashtag system we decided to use! I think it works just as well.

- moderation is off for anyone "in the room" atm. We can add other community members to the list after the soft launch.

**Comment by JosephMcArthur** [comment]
> Do we need labels for issues on the main repo? I've restructured all the searches and links so that they are according to the #hashtag system we decided to use! I think it works just as well.

sure lets not worry for now

**Comment by JosephMcArthur** [comment]
Issue template in the main repo new formats correctly again. Have " in a comment will make it show up.

**Comment by JosephMcArthur** [comment]
The email looks fine. All I'd suggest is the bring back the formatting in the metadata section that would help it show better on Github & be a bit more condensed. I put this in an email draft @lorrainechu3n

**Comment by JosephMcArthur** [comment]
I THINK from everything on the main site, with how it's currently configured, we're all set. 

Of course, I think we want to still be making changes - BUT - not today probably. Let's get this shipped and in people's hands.
